---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE, 
  message = FALSE, 
  warning = FALSE,
  comment = "#>"
)
library(stringr)
library(glue)
```

# Readme

Chapter Notes and End of Chapter Solutions for the book **Statistical Rethinking by Richard McElreath, 2nd Edition**. 

These are currently using package `rethinking`. 


```{r}
chapters <- list.files(pattern = "^Chapter\\d+")
chapters <- gtools::mixedsort(chapters)
directory <- data.frame(Chapters = chapters, 
                        `Chapter Notes` = NA, 
                        `Chapter EoC Questions` = NA, 
                        check.names = FALSE, stringsAsFactors = FALSE)

for(i in seq_along(chapters)){
     files <- list.files(chapters[i], include.dirs = FALSE, full.names = TRUE)
     
     # search for Chapter_##_.html (main chapter note + models)
     if(any(grepl("Chapter_\\d+\\.html$", files,ignore.case = TRUE))){
       # if any such file found, find it and attach beginning html
       note <- grep("Chapter_\\d+\\.html$", files, value = TRUE, ignore.case = TRUE)
       note <- glue("https://adromine.github.io/Statistical-Rethinking-Code/{note}")
     } else {
       # else there's probably a .R file (for the beginning chapters)
       note <- grep("Chapter_\\d+\\.R$", files, value = TRUE)
     }
     
     directory[i, 2] <- glue("[link]({note})")
     html <- grep("Chapter_\\d+_EoC\\.html", files, value = TRUE, ignore.case = TRUE)
     if(length(html) > 0)
       directory[i, 3] <- glue("[link](https://adromine.github.io/Statistical-Rethinking-Code/{html})")
     else directory[i, 3] <- "WIP"
}

directory$Chapters <- str_replace(directory$Chapters, "Chapter", "Chapter ")
knitr::kable(directory)
```

